version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /docker-credentials/password
    DOCKER_REGISTRY_URL: /docker-registry/url
    SONAR_TOKEN: /cd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Performing Trivy file scan before building the image..."

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."

  post_build:
    commands:
      - aws ses send-email \
          --from "prasadzagade305@gmail.com" \
          --destination "ToAddresses=prasadzagade305@gmail.com" \
          --message "Subject={Data=CodeBuild Status: $CODEBUILD_BUILD_ID},Body={Text={Data=Build status: $CODEBUILD_BUILD_STATUS}}" \
          --region "ap-south-1"

artifacts:
  files:
    - appspec.yaml
