---
version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token
phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Performing Trivy file scan before building the image..."
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
post_build:
  commands:
    - echo "Sending email notification with build status..."
    - |
      aws ses send-email \
        --from "prasadzagade305@gmail.com" \
        --to "prasadzagade305@gmail.com" \
        --subject "CodeBuild Status: $CODEBUILD_BUILD_ID" \
        --text "Build status: $CODEBUILD_BUILD_STATUS" \
        --region "ap-south-1"  # Update if using a different AWS region
artifacts:
  files:
    - appspec.yaml
